// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_test.go
//
// Generated by this command:
//
//	mockgen -source=interfaces_test.go -destination=mocks/transformfunc_interface.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransformFunc is a mock of TransformFunc interface.
type MockTransformFunc struct {
	ctrl     *gomock.Controller
	recorder *MockTransformFuncMockRecorder
	isgomock struct{}
}

// MockTransformFuncMockRecorder is the mock recorder for MockTransformFunc.
type MockTransformFuncMockRecorder struct {
	mock *MockTransformFunc
}

// NewMockTransformFunc creates a new mock instance.
func NewMockTransformFunc(ctrl *gomock.Controller) *MockTransformFunc {
	mock := &MockTransformFunc{ctrl: ctrl}
	mock.recorder = &MockTransformFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformFunc) EXPECT() *MockTransformFuncMockRecorder {
	return m.recorder
}

// TransformFunc mocks base method.
func (m *MockTransformFunc) TransformFunc(arg0 any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformFunc", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransformFunc indicates an expected call of TransformFunc.
func (mr *MockTransformFuncMockRecorder) TransformFunc(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformFunc", reflect.TypeOf((*MockTransformFunc)(nil).TransformFunc), arg0)
}
