apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: namespace-lister-cert
spec:
  dnsNames:
  - namespace-lister.namespace-lister.svc
  - namespace-lister.namespace-lister.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-cluster-issuer
  secretName: namespace-lister-cert
