apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-lister
  namespace: namespace-lister
  labels:
    apps: namespace-lister
spec:
  selector:
    matchLabels:
      apps: namespace-lister
  replicas: 1
  template:
    metadata:
      labels:
        apps: namespace-lister
    spec:
      # securityContext:
      #   runAsNonRoot: true
      serviceAccountName: namespace-lister
      containers:
      - args:
        - -enable-tls
        - -cert-path=/var/tls/tls.crt
        - -key-path=/var/tls/tls.key
        image: namespace-lister:latest
        name: namespace-lister
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: "0"
        # - name: AUTH_USERNAME_HEADER
        #   value: "X-User"
        # - name: CACHE_NAMESPACE_LABELSELECTOR
        #   value: 'konflux.dev/type=user'
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
        volumeMounts:
        - name: tls
          mountPath: /var/tls
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: tls
        secret:
          secretName: namespace-lister-cert
