apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificate.yaml
- deployment.yaml
- service.yaml
- metrics-service.yaml
- namespace.yaml
- rbac.yaml
- network-policy-egress-allow-apiserver.yaml
namespace: namespace-lister
replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: namespace-lister
  targets:
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: namespace-lister-cert
      version: v1
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: namespace-lister
  targets:
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: namespace-lister-cert
      version: v1
