apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificate.yaml
- deployment.yaml
- service.yaml
- namespace.yaml
- rbac.yaml
namespace: namespace-lister
replacements:
- source:
    kind: Service
    name: namespace-lister
    fieldPath: metadata.name
  targets:
  - select:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: namespace-lister-cert
    fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: "."
      index: 0
- source:
    kind: Service
    name: namespace-lister
    fieldPath: metadata.namespace
  targets:
  - select:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: namespace-lister-cert
    fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: "."
      index: 1
