apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert-auth
spec:
  dnsNames:
  - localhost
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-cluster-issuer
  secretName: serving-cert-auth
